---@meta

---@class EntitySensor.FoodData
---@field hungry boolean
---@field saturation number
---@field hunger number

---@class EntitySensor.EntityData : Position3D
---@field displayName string
---@field name string
---@field id string
---@field motionX number
---@field motionY number
---@field motionZ number
---@field yaw number
---@field pitch number

---@class EntitySensor.EntityMetadata : EntitySensor.EntityData
---@field maxHealth number
---@field health number
---@field withinBlock Position3D
---@field isAlive boolean
---@field isDead boolean
---@field isInWater boolean
---@field isWet boolean
---@field isBurning boolean
---@field allowFlying? boolean
---@field isFlying? boolean
---@field isElytraFlying boolean
---@field isRiding boolean
---@field isOnLadder boolean
---@field isSprinting boolean
---@field isChild boolean
---@field isSleeping boolean
---@field isAirborne boolean
---@field isSneaking boolean
---@field armor table<string, Inventory.Item>
---@field potionEffects string[]
---@field food? EntitySensor.FoodData
---@field heldItem? Inventory.Item
---@field offhandItem? Inventory.Item
---@field flySpeed? number
---@field walkSpeed? number