---@meta

---@alias os.locale
---| '"ingame"'
---| '"utc"'
---| '"local"'

---@class os.timestampTable
---@field sec integer
---@field min integer
---@field hour integer
---@field day integer
---@field month integer
---@field year integer
---@field wday integer
---@field yday integer
---@field isdst boolean

---@alias os.event
---| '"alaram"'
---| '"char"'
---| '"computer_command"'
---| '"disk"'
---| '"disk_eject"'
---| '"file_transfer"'
---| '"http_check"'
---| '"http_failure"'
---| '"http_success"'
---| '"key"'
---| '"key_up"'
---| '"modem_message"'
---| '"monitor_resize"'
---| '"monitor_touch"'
---| '"mouse_click"'
---| '"mouse_drag"'
---| '"mouse_scroll"'
---| '"mouse_up"'
---| '"paste"'
---| '"peripheral"'
---| '"peripheral_detach"'
---| '"rednet_message"'
---| '"redstone"'
---| '"speaker_audio_empty"'
---| '"task_complete"'
---| '"term_resize"'
---| '"timer"'
---| '"turtle_inventory"'
---| '"websocket_closed"'
---| '"websocket_failure"'
---| '"websocket_message"'
---| '"websocket_success"'

---@alias os.rawEvent os.event
---|'"terminate"'