---@meta

---@class plethora.entity.FoodData
---@field hungry boolean
---@field saturation number
---@field hunger number

---@class plethora.entity.EntityData
---@field x number
---@field y number
---@field z number
---@field displayName string
---@field name string
---@field id string
---@field motionX number
---@field motionY number
---@field motionZ number
---@field yaw number
---@field pitch number

---@class plethora.entity.EntityMetadata : plethora.entity.EntityData
---@field maxHealth number
---@field health number
---@field withinBlock { x: number, y: number, z: number }
---@field isAlive boolean
---@field isDead boolean
---@field isInWater boolean
---@field isWet boolean
---@field isBurning boolean
---@field allowFlying? boolean
---@field isFlying? boolean
---@field isElytraFlying boolean
---@field isRiding boolean
---@field isOnLadder boolean
---@field isSprinting boolean
---@field isChild boolean
---@field isSleeping boolean
---@field isAirborne boolean
---@field isSneaking boolean
---@field armor table<string, plethora.ItemStack>
---@field potionEffects string[]
---@field food? plethora.entity.FoodData
---@field heldItem? plethora.ItemStack
---@field offhandItem? plethora.ItemStack
---@field flySpeed? number
---@field walkSpeed? number
