---@meta

---@class OverlayGlasses.Canvas2d.Group		: Canvas.BaseObject, Canvas.Positional2D, OverlayGlasses.Canvas2d
---@class OverlayGlasses.Canvas2d.Item		: Canvas.BaseObject, Canvas.Scalable, Canvas.Positional2D, Canvas.ItemObject
---@class OverlayGlasses.Canvas2d.Text		: Canvas.BaseObject, Canvas.Colorable, Canvas.Scalable, Canvas.Positional2D, Canvas.Textual
---@class OverlayGlasses.Canvas2d.Dot		: Canvas.BaseObject, Canvas.Colorable, Canvas.Scalable, Canvas.Positional2D
---@class OverlayGlasses.Canvas2d.Lines		: Canvas.BaseObject, Canvas.Colorable, Canvas.MultipointResizable2D, Canvas.Scalable
---@class OverlayGlasses.Canvas2d.Polygon	: Canvas.BaseObject, Canvas.Colorable, Canvas.MultipointResizable2D
---@class OverlayGlasses.Canvas2d.Line		: Canvas.BaseObject, Canvas.Colorable, Canvas.Multipoint2D
---@class OverlayGlasses.Canvas2d.Triangle	: Canvas.BaseObject, Canvas.Colorable, Canvas.Multipoint2D
---@class OverlayGlasses.Canvas2d.Rectangle	: Canvas.BaseObject, Canvas.Colorable, Canvas.Positional2D, Canvas.Resizable2D
